### ISSUE TITLE
Main.py 

### ISSUE THREAD

**Issue by AmaOwusua** [AmaOwusua/snake-game#2]
@aappau  I cannot run the code because I think there is a problem importing the library.

I upgraded my pip and installed the windows version form of the "curses library " using this command : pip install windows-curses
but it still didn"t work .

Please do you have any idea with this issue?

**ERROR**
Traceback (most recent call last):
  File "C:\Users\glenn\Documents\Prj\Snake-game\main.py", line 1, in <module>
    import curses
  File "C:\Users\glenn\AppData\Local\Programs\Python\Python39-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by aappau** [comment]
I think it's a problem with the python version on your computer. I installed the library on my windows 10 computer and I was able to pull and run your code without any errors.

I'm using Python 3.8.2

Enter this command in the terminal to check the version of python on your computer:
`python -V`

Reply with your python version.

**Comment by AmaOwusua** [comment]
Python 3.9.1

**Comment by aappau** [comment]
I've added a new file to the repository. It contains the missing modules. Install and let's see if it works

1.  Pull latest code to your local environment
`git pull`

2. Install Packages
`pip install -r requirements.txt`

3. Run the code again and let me know the results

**Comment by AmaOwusua** [comment]
Result:

Requirement already satisfied: windows-curses==2.3.0 in c:\users\glenn\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 1)) (2.3.0)

**Comment by aappau** [comment]
Ok that's weird. Let's setup a Teams or Zoom call for tomorrow to do a screen share and figure it out together.

**Comment by AmaOwusua** [comment]
Alright

**Comment by AmaOwusua** [comment]
Alright.
Result now :
Redirection is not supported.

**Comment by AmaOwusua** [comment]
It is working now. I figured it out. 
Thanks
